name: action-publish-cloudflare-worker
description: Action to deploy a bundle to Cloudflare workers via API
inputs:
  apiToken:
    description: Cloudflare API token
    required: true
  scriptPath:
    description: bundled script file path
    required: true
  wranglerTomlPath:
    description: wrangler.toml file path
    required: true
  environment:
    description: Cloudflare environment name
    required: true
runs:
  using: node16
  main: dist/index.js
