name: action-publish-cloudflare-worker
description: action-publish-cloudflare-worker
inputs:
  foo:
    description: foo
    required: false
outputs:
  bar:
    description: bar
runs:
  using: node16
  main: dist/index.js
